 ° ± ² ³ ´ µ ¶ · ¸ ¹ º » ¼ ½ ¾ ¿ À Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û Ü Ý Þ ß 
10 
 7fÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ´ 74Slackel Live          7f ÃÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ70¿10
 7f³70 Welcome to Slackel Live             Please select the language of your       ³10
 7f³70 choice in the menu below. The menu can be navigated by using the up and    ³10
 7f³70 down arrows keys on your keyboard.  You can pass additional kernel         ³10
 7f³70 arguments using the text box below.  A list of suggested kernel arguments  ³10
 7f³70 can be found by pressing F2. Once you have chosen your language and kernel ³10
 7f³70 arguments, press the <return> key to boot into Slackel Live.  Enjoy!!        ³10
 7f³70                                                                            ³10
 7f³70                                                                            ³10
 7f³70                                                                            ³10
 7f³70            ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ7f¿70              ³10
 7f³70            ³70          This is where the menu goes           7f³70             ³10
 7f³70            ³701e            (active colour)                     7f³70              ³10
 7f³70            ³70           (inactive colour)                    7f³70              ³10
 7f³70            ³70                                                1e7f³70             ³10
 7f³70            À7fÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ70              ³10
 7f³70                                                                            ³10
 7f³70                                                                            ³10
 7f³70                                                                            ³10
 7f³70 Boot: 35                                                                  70   ³10
 7f³70                                                                            ³10
 7f³70 Help: [71F170-General]  [71F270-Params]                                            ³10
 7fÀ70ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ10
