ATTENTION: 

The root password is live
The user one password is one.

New root password can be set using the 
"rootpw=YOURPASSWORD" boot parameter (without the quotes).


If experiencing problems with some graphic cards, 
try the following boot parameters (without the quotes):

"i915.modeset=0"  (for INTEL cards)
"radeon.modeset=1" (for ATI cards)







This Kernel has PAE enabled and will not run on machines 
which does not support PAE (e.g. Pentium M), sorry!


Persistent home is supported by boot parameter "home=directory".

Persistent system is supported by boot parameter "changes=directory"
(e.g. "changes=persistence")
